language: php
php:
    - 5.6
    - 5.5
    - hhvm
    
services:
  - mysql

before_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - composer install
    - mysql -e 'create database phpmvc;'
    - mysql phpmvc < user.sql
    

script:
    #- phpunit --bootstrap test/config.php test
     - phpunit --bootstrap test/config.php --coverage-clover coverage.clover test
    #- phpunit --bootstrap test/config.php --coverage-html ./test/code-coverage test/

after_script:
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover